const APPConfig = {
  // API_URL: "http://173.212.250.62/betting/ap-admin/public/api",
  API_URL: "https://betting.aercjbp.com/ap-admin/public/api",
};
// 752d253c74fc59219fd336b881fdd13c
const ApiEndPoints = {
  ApiKey: "752d253c74fc59219fd336b881fdd13c",
  // ApiKey: "f9af698cc538367931ebfe9e11c6b3cc",
  Login: `${APPConfig.API_URL}/login`,
  Register: `${APPConfig.API_URL}/register`,
  ForgotPassword: `${APPConfig.API_URL}/forgot-password`,
  VerifyOtp: `${APPConfig.API_URL}/forgot-verify-email-otp`,
  ResetPassword: `${APPConfig.API_URL}/reset-password`,
  ProfileGet: `${APPConfig.API_URL}/profile`,
  ProfileUpdate: `${APPConfig.API_URL}/update-profile`,
  BankUpdate: `${APPConfig.API_URL}/update-bank-info`,
  BankInfo: `${APPConfig.API_URL}/bank-info`,
  PlaceBet: `${APPConfig.API_URL}/place-bet`,
  Get_Market: `${APPConfig.API_URL}/markets-by-game/`,
  BettingHistory: `${APPConfig.API_URL}/bet-history`,
  GetNews: `${APPConfig.API_URL}/news`,
  LeagueList: `${APPConfig.API_URL}/leagues`,
  CreateLeague: `${APPConfig.API_URL}/create-league`,
  LeagueDetail: `${APPConfig.API_URL}/league/`,
  DeleteLeague: `${APPConfig.API_URL}/league-delete/`,
  LeaveLeague: `${APPConfig.API_URL}/league-leave/`,
  AcceptInvite: `${APPConfig.API_URL}/league-accept-invite`,
  LeagueUnits: `${APPConfig.API_URL}/league-member/`,
  getOddsBygame: `${APPConfig.API_URL}/odds-by-game/`,
  UpdateUnit: `${APPConfig.API_URL}/update-unit-league/`,
  GlobalLeagues: `${APPConfig.API_URL}/global-leagues`,
  GlobalLeagueDetails: `${APPConfig.API_URL}/global-league/`,
  GlobalLeagueJoin: `${APPConfig.API_URL}/global-league-join/`,
  GlobalLeagueLeave: `${APPConfig.API_URL}/global-league-leave/`,
  GlobalAcceptInvite: `${APPConfig.API_URL}/global-accept-invite/`,
  getScore: `${APPConfig.API_URL}/score-by-game/`,
  getScoreById: `${APPConfig.API_URL}/score-by-event/`,
  getOddsById: `${APPConfig.API_URL}/odds-by-event/`,
  getTeams: `${APPConfig.API_URL}/team-by-game/`,
  getGames: `${APPConfig.API_URL}/games`,
  addToWishlist: `${APPConfig.API_URL}/add-to-wishlist`,
  deleteWishlist: `${APPConfig.API_URL}/delete-wishlist/`,
  wishlist: `${APPConfig.API_URL}/wishlist`,
};

export default ApiEndPoints;
